Updated to DrevOps 1.17

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -17,23 +17,25 @@ commands:
     usage: Build or rebuild the project.
     cmd: |
       ahoy confirm "Running this command will remove your current database and files. Are you sure?" &&
-      ./scripts/drevops/build.sh
+      ./scripts/drevops/build.sh &&
+      ahoy info
 
   info:
     usage: Show information about this project.
     cmd: |
-      docker-compose exec \
-        -e COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-${PWD##*/}} \
-        -e DREVOPS_HOST_DB_PORT=$(docker port $(docker-compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2) \
-        -e DREVOPS_DRUPAL_SHOW_LOGIN_LINK=${DREVOPS_DRUPAL_SHOW_LOGIN_LINK} \
-        cli ./scripts/drevops/info.sh "$@"
+      COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-${PWD##*/}} \
+      DREVOPS_HOST_DB_PORT=$(docker compose port mariadb 3306 2>/dev/null | cut -d : -f 2) \
+      DREVOPS_HOST_SOLR_PORT=$(docker compose port solr 8983 2>/dev/null | cut -d : -f 2) \
+      DREVOPS_HOST_HAS_SEQUELACE=$(uname -a | grep -i -q darwin && mdfind -name 'Sequel Ace' 2>/dev/null | grep -q "Ace" && echo 1 || true) \
+      DREVOPS_DRUPAL_SHOW_LOGIN_LINK=${DREVOPS_DRUPAL_SHOW_LOGIN_LINK} \
+      ahoy cli ./scripts/drevops/info.sh "$@"
 
   db:
     usage: Open DB in Sequel Ace.
     cmd: |
-      uname -a | grep -i -q darwin && mdfind -name 'Sequel Ace'|grep -q "Ace" \
-      && DREVOPS_HOST_DB_PORT="$(docker port $(docker-compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
-      && open "mysql://${DREVOPS_MARIADB_USER}:${DREVOPS_MARIADB_PASSWORD}@127.0.0.1:${DREVOPS_HOST_DB_PORT}/drupal" -a "Sequel Ace" \
+      uname -a | grep -i -q darwin && mdfind -name 'Sequel Ace' 2>/dev/null |grep -q "Ace" \
+      && DREVOPS_HOST_DB_PORT="$(docker port $(docker compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
+      && open "mysql://${MARIADB_USERNAME:-drupal}:${MARIADB_PASSWORD:-drupal}@127.0.0.1:${DREVOPS_HOST_DB_PORT}/drupal" -a "Sequel Ace" \
       || echo "Not a supported OS or Sequel Ace is not installed."
 
   # ----------------------------------------------------------------------------
@@ -43,32 +45,32 @@ commands:
   up:
     usage: Build and start Docker containers.
     cmd: |
-      docker-compose up -d "$@" && if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
-      mkdir -p docroot/sites/default/files && docker-compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > /app/docroot/sites/default/files/livereload.sock'
+      docker compose up -d "$@" && if docker compose logs | grep -q "\[Error\]"; then exit 1; fi
+      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > /app/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
 
   down:
     usage: Stop Docker containers and remove container, images, volumes and networks.
     cmd: |
       ahoy confirm "Running this command will remove your current database. Are you sure?" &&
-      if [ -f "docker-compose.yml" ]; then docker-compose down --volumes > /dev/null 2>&1; fi
+      if [ -f "docker-compose.yml" ]; then docker compose down --remove-orphans --volumes > /dev/null 2>&1; fi
 
   start:
     usage: Start existing Docker containers.
     cmd: |
-      docker-compose start "$@"
-      mkdir -p docroot/sites/default/files && docker-compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > /app/docroot/sites/default/files/livereload.sock'
+      docker compose start "$@"
+      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > /app/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
 
   stop:
     usage: Stop running Docker containers.
-    cmd: docker-compose stop "$@"
+    cmd: docker compose stop "$@"
 
   restart:
     usage: Restart stopped or running Docker containers.
-    cmd: docker-compose restart "$@"
+    cmd: docker compose restart "$@"
 
   logs:
     usage: Show Docker logs for services.
-    cmd: docker-compose logs "$@"
+    cmd: docker compose logs "$@"
 
   pull:
     usage: Pull latest Docker images.
@@ -77,23 +79,25 @@ commands:
   cli:
     usage: Start a shell or run a command inside the CLI service container.
     # This will drop into shell if no arguments are supplied to this command.
-    # If arguments supplied, a new shell with DREVOPS_*, COMPOSE_* and TERM
-    # environment variables will be started. This allows passing of the environment
-    # variables to Ahoy commands which will then be forwarded to the container.
-    # Escape double quotes with \" (slash double-quote) when passing arguments with spaces.
-    cmd: if \[ "${#}" -ne 0 \]; then docker-compose exec $(env | cut -f1 -d= | grep "DREVOPS_\|COMPOSE_\|TERM" | sed 's/^/-e /') -T cli bash -c "$*"; else docker-compose exec cli bash; fi
+    # If arguments supplied, a new shell with TERM, COMPOSE_*, GITHUB_*,
+    # DOCKER_*, DRUPAL_* and DREVOPS_* environment variables will be started.
+    # This allows passing of the environment variables to Ahoy commands which
+    # will then be forwarded to the container.
+    # Escape double quotes with \" (slash double-quote) when passing arguments
+    # with spaces.
+    cmd: if \[ "${#}" -ne 0 \]; then docker compose exec $(env | cut -f1 -d= | grep "TERM\|COMPOSE_\|GITHUB_\|DOCKER_\DRUPAL_\|DREVOPS_" | sed 's/^/-e /') -T cli bash -c "$*"; else docker compose exec cli bash; fi
 
   composer:
     usage: Run Composer commands in the CLI service container.
-    cmd: docker-compose exec -T cli composer "$@"
+    cmd: ahoy cli composer "$@"
 
   drush:
     usage: Run Drush commands in the CLI service container.
-    cmd: docker-compose exec -T cli bash -c "drush -l ${DREVOPS_LOCALDEV_URL} $*"
+    cmd: ahoy cli "drush -l \${DREVOPS_LOCALDEV_URL} $*"
 
   flush-redis:
     usage: Flush Redis cache.
-    cmd: docker-compose exec redis redis-cli flushall
+    cmd: docker compose exec redis redis-cli flushall
 
   # ----------------------------------------------------------------------------
   # Application commands.
@@ -102,133 +106,111 @@ commands:
   login:
     usage: Login to a website.
     # Unblock user 1 and generate a one time login link.
-    cmd: ahoy cli ./scripts/drevops/drupal-login.sh
+    cmd: ahoy cli ./scripts/drevops/login.sh
 
+  download-db:
+    usage: Download database.
+    cmd: ./scripts/drevops/download-db.sh
 
   reload-db:
     usage: Reload the database container using local database image.
     cmd: |
       ahoy confirm "Running this command will replace your current database. Are you sure?" &&
-      docker-compose rm -f -s -v mariadb && ahoy up -- --build mariadb && ahoy install-site && ahoy info && ahoy login ||
-      echo "The operation was canceled."
+      docker compose rm -f -s -v mariadb \
+        && ahoy up -- --build mariadb \
+        && ahoy up wait_dependencies \
+        && sleep 15 \
+        && ahoy provision \
+        && ahoy info \
+        && ahoy login
 
-  install-site:
-    usage: Install a site.
-    cmd: |
-      docker-compose exec \
-      -e DREVOPS_DRUPAL_VERSION=${DREVOPS_DRUPAL_VERSION:-} \
-      -e DREVOPS_DRUPAL_INSTALL_OPERATIONS_SKIP=${DREVOPS_DRUPAL_INSTALL_OPERATIONS_SKIP:-} \
-      -e DREVOPS_DRUPAL_INSTALL_OVERRIDE_EXISTING_DB=${DREVOPS_DRUPAL_INSTALL_OVERRIDE_EXISTING_DB:-0} \
-      -e DREVOPS_DRUPAL_PROFILE=${DREVOPS_DRUPAL_PROFILE:-standard} \
-      -e CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=${CIVICTHEME_SUBTHEME_ACTIVATION_SKIP:-0} \
-      -e CIVICTHEME_SUBTHEME_FE_SKIP=${CIVICTHEME_SUBTHEME_FE_SKIP:-} \
-      -e CIVICTHEME_GENERATED_CONTENT_CREATE_SKIP=${CIVICTHEME_GENERATED_CONTENT_CREATE_SKIP:-} \
-      -e CIVICTHEME_CONTENT_PROFILE=${CIVICTHEME_CONTENT_PROFILE:-} \
-      -T cli ./scripts/drevops/drupal-install-site.sh
+  provision:
+    usage: Provision a site from the database dump or profile.
+    cmd: ahoy cli ./scripts/drevops/provision.sh
 
   export-db:
-    usage: Export database dump or database image (DREVOPS_DB_DOCKER_IMAGE variable must be set).
-    cmd: |
-      [ -z "${DREVOPS_DB_DOCKER_IMAGE}" ] && docker-compose exec -e DREVOPS_DB_DIR=${DREVOPS_DB_DIR:-} -T cli ./scripts/drevops/export-db-file.sh "$@" || \
-      ( DREVOPS_DB_EXPORT_DOCKER_IMAGE="${DREVOPS_DB_DOCKER_IMAGE}" ./scripts/drevops/export-db-docker.sh "$@";
-      if [ "${DREVOPS_EXPORT_DB_DOCKER_DEPLOY_PROCEED}" = "1" ]; then DREVOPS_DEPLOY_DOCKER_MAP=mariadb=${DREVOPS_DB_DOCKER_IMAGE} DREVOPS_DEPLOY_DOCKER_IMAGE_TAG=${DREVOPS_DOCKER_IMAGE_TAG} ./scripts/drevops/deploy-docker.sh; fi )
+    usage: Export database dump or database image (if DREVOPS_DB_DOCKER_IMAGE variable is set).
+    cmd: ./scripts/drevops/export-db.sh "$@"
 
   pull-db:
     usage: Download database image with the latest nightly dump. Run "ahoy reload-db" to reload DB in the running stack.
     cmd: |
       [ -n "${DREVOPS_DB_DOCKER_IMAGE}" ] && docker pull $DREVOPS_DB_DOCKER_IMAGE
 
-  clean:
-    usage: Remove Docker containers and all build files.
-    cmd: ahoy down && ./scripts/drevops/clean.sh
-
   reset:
-    usage: "Remove containers, all build, uncommitted files."
+    usage: "Remove containers, all build files. Use with `hard` to reset repository to the last commit."
     cmd: |
-      ahoy confirm "All containers, build and uncomitted files will be removed, repository will be reset to the last commit. Proceed?" \
-      && ahoy clean && ./scripts/drevops/reset.sh || echo "The operation was canceled."
+      ahoy confirm "All containers and build files will be removed. Proceed?" &&
+      AHOY_CONFIRM_RESPONSE=y ahoy down && ./scripts/drevops/reset.sh "$@"
 
   fei:
     usage: Install front-end assets.
     cmd: |
-      [ "${CIVICTHEME_LIBRARY_INSTALL_SKIP}" != "1" ] && ahoy cli "npm --prefix docroot/themes/contrib/${DREVOPS_DRUPAL_THEME}/civictheme_library install"
-      ahoy cli "npm --prefix docroot/themes/contrib/${DREVOPS_DRUPAL_THEME} install"
+      [ "${CIVICTHEME_LIBRARY_INSTALL_SKIP}" != "1" ] && ahoy cli "npm --prefix web/themes/contrib/${DRUPAL_THEME}/civictheme_library install"
+      ahoy cli "npm --prefix web/themes/contrib/${DRUPAL_THEME} install"
 
   fe:
     usage: Build front-end assets.
     cmd: |
-      [ "${CIVICTHEME_LIBRARY_INSTALL_SKIP}" != "1" ] && ahoy cli "cd docroot/themes/contrib/${DREVOPS_DRUPAL_THEME}/civictheme_library && npm run build"
-      ahoy cli "cd docroot/themes/contrib/${DREVOPS_DRUPAL_THEME} && npm run build"
+      [ "${CIVICTHEME_LIBRARY_INSTALL_SKIP}" != "1" ] && ahoy cli "cd web/themes/contrib/${DRUPAL_THEME}/civictheme_library && npm run build"
+      ahoy cli "cd web/themes/contrib/${DRUPAL_THEME} && npm run build"
 
   lint:
     usage: Lint back-end and front-end code.
-    cmd: ahoy cli ./scripts/drevops/lint.sh "$@"
+    cmd: ahoy lint-be && ahoy lint-fe
 
   lint-be:
     usage: Lint back-end code.
-    cmd: ahoy cli ./scripts/drevops/lint.sh be
+    cmd: |
+      ahoy cli vendor/bin/phpcs
+      ahoy cli vendor/bin/phpstan
+      ahoy cli vendor/bin/phpmd . text phpmd.xml
 
   lint-fe:
     usage: Lint front-end code.
-    cmd: ahoy cli ./scripts/drevops/lint.sh fe
+    cmd: |
+      ahoy cli vendor/bin/twigcs
+      ahoy cli "npm run --prefix \${DREVOPS_WEBROOT}/themes/custom/\${DRUPAL_THEME} lint"
 
   lint-config:
     usage: Lint config
-    cmd: ahoy cli ./scripts/drevops/lint.sh config
+    cmd: |
+      ahoy cli ./scripts/lint-theme-config.sh
+      ahoy cli "./vendor/bin/drush inspect_config civictheme.settings --detail --only-error"
 
   test:
     usage: Run all tests.
     cmd: ahoy test-unit && ahoy test-kernel && ahoy test-functional && ahoy test-bdd
 
-  test-fe:
-    usage: Run front-end tests.
-    cmd: ahoy cli "DREVOPS_TEST_TYPE=fe DREVOPS_TEST_REPORTS_DIR=${DREVOPS_TEST_REPORTS_DIR} ./scripts/drevops/test.sh $@"
-
   test-unit:
     usage: Run PhpUnit unit tests.
-    cmd: ahoy cli "DREVOPS_TEST_TYPE=unit DREVOPS_TEST_REPORTS_DIR=${DREVOPS_TEST_REPORTS_DIR} ./scripts/drevops/test.sh $@"
+    cmd: ahoy cli vendor/bin/phpunit --testsuite=unit "$@"
 
   test-kernel:
     usage: Run PhpUnit kernel tests.
-    cmd: ahoy cli "DREVOPS_TEST_TYPE=kernel DREVOPS_TEST_ARTIFACT_DIR=${DREVOPS_TEST_ARTIFACT_DIR} DREVOPS_TEST_REPORTS_DIR=${DREVOPS_TEST_REPORTS_DIR} ./scripts/drevops/test.sh $@"
+    cmd: ahoy cli vendor/bin/phpunit --testsuite=kernel "$@"
 
   test-functional:
     usage: Run PhpUnit functional tests.
-    cmd: ahoy cli "DREVOPS_TEST_TYPE=functional DREVOPS_TEST_ARTIFACT_DIR=${DREVOPS_TEST_ARTIFACT_DIR} DREVOPS_TEST_REPORTS_DIR=${DREVOPS_TEST_REPORTS_DIR} ./scripts/drevops/test.sh $@"
+    cmd: ahoy cli vendor/bin/phpunit --testsuite=functional "$@"
 
   test-bdd:
     usage: Run BDD tests.
-    cmd: ahoy cli "DREVOPS_TEST_TYPE=bdd DREVOPS_TEST_ARTIFACT_DIR=${DREVOPS_TEST_ARTIFACT_DIR} DREVOPS_TEST_REPORTS_DIR=${DREVOPS_TEST_REPORTS_DIR} DREVOPS_TEST_BEHAT_PROFILE=${DREVOPS_TEST_BEHAT_PROFILE:-} DREVOPS_TEST_BEHAT_FORMAT=${DREVOPS_TEST_BEHAT_FORMAT:-} DREVOPS_TEST_BEHAT_PARALLEL_INDEX=${DREVOPS_TEST_BEHAT_PARALLEL_INDEX:-} BEHAT_SCREENSHOT_PURGE=${BEHAT_SCREENSHOT_PURGE-} DREVOPS_TEST_BEHAT_TAGS=${DREVOPS_TEST_BEHAT_TAGS-} ./scripts/drevops/test.sh $@"
+    cmd: ahoy cli php -d memory_limit=-1 vendor/bin/behat --colors "$@"
 
   test-bats:
     usage: Run Bats tests (host only).
-    cmd: bats --tap tests/bats/
-
+    cmd: ./scripts/test-tooling.sh
 
   debug:
     usage: Enable PHP Xdebug.
-    cmd: ahoy cli php -v | grep -q Xdebug || XDEBUG_ENABLE=true ahoy up cli php nginx && ahoy cli php -v | grep -q Xdebug && echo "Enabled debug confguration. Use 'ahoy up' to disable."
-
-  export-config:
-    usage: Export theme config.
-    cmd: |
-      ahoy cli "./scripts/update-theme-config.sh"
-      ahoy drush cde civictheme_dev || true
-      if ahoy drush pm:list --status=Enabled --field=name | grep -q 'cs_generated_content'; then
-        ahoy drush cde cs_generated_content || true
-      fi
-
-  export-content:
-    usage: Export content (run with CIVICTHEME_CONTENT_PROFILE=corporate ahoy install-site) .
-    cmd: |
-      ahoy confirm "This will uninstall several modules and users. Proceed?" \
-      && ahoy cli "CIVICTHEME_CONTENT_PROFILE=${CIVICTHEME_CONTENT_PROFILE:-default} ./scripts/update-default-content.sh" || echo "The operation was canceled."
+    cmd: ahoy cli php -v | grep -q Xdebug || XDEBUG_ENABLE=true ahoy up cli php nginx && ahoy cli php -v | grep -q Xdebug && echo "Enabled debug configuration. Use 'ahoy up' to disable."
 
   deploy:
     usage: Run remote deployment procedures.
     cmd: |
-      ahoy confirm "Deployment usually runs in CI. Are you sure you want to proceed with manual deployment? (Run as DREVOPS_DEPLOY_PROCEED=1 ahoy deploy [type1,[type2..]], where [type] is 'code', 'docker', 'webhook')" \
-      && ./scripts/drevops/deploy.sh "$@" || echo "The operation was canceled."
+      ahoy confirm "Deployment usually runs in CI. Are you sure you want to proceed with manual deployment? (Run as DREVOPS_DEPLOY_PROCEED=1 ahoy deploy [type1,[type2..]], where [type] is 'code', 'docker', 'webhook')" &&
+      ./scripts/drevops/deploy.sh "$@"
 
   github-labels:
     usage: Update project's GitHub labels.
@@ -238,21 +220,34 @@ commands:
     usage: Find problems with current project setup.
     cmd: ./scripts/drevops/doctor.sh "$@"
 
-  update:
-    usage: Update development stack.
-    cmd: ahoy confirm "Some committed files may become overwritten. Proceed?" && ./scripts/drevops/update.sh || echo "The operation was canceled."
+  update-drevops:
+    usage: Update DrevOps stack.
+    cmd: |
+      ahoy confirm "Some committed files may become overwritten. Proceed?" &&
+      ./scripts/drevops/update-drevops.sh $@
 
   local:
     usage: Custom local commands. See `ahoy local help`.
     cmd: |
-      if [ -f .ahoy.local.yml ]; then ahoy -f ".ahoy.local.yml" "$@"; else echo ".ahoy.local.yml does not exist. Copy default.ahoy.local.yml to .ahoy.local.yml and rerun this command."; fi
+      if [ -f .ahoy.local.yml ]; then
+        ahoy -f ".ahoy.local.yml" "$@"
+      else
+        echo ".ahoy.local.yml does not exist."
+        echo "Copy .ahoy.local.example.yml to .ahoy.local.yml and rerun this command.";
+      fi
 
   # ----------------------------------------------------------------------------
   # Utilities.
   # ----------------------------------------------------------------------------
   confirm:
     cmd: |
-      [ -z "$DREVOPS_AHOY_CONFIRM_RESPONSE" ] && read -r -p "$1 [y/N] " DREVOPS_AHOY_CONFIRM_RESPONSE; [ "$DREVOPS_AHOY_CONFIRM_RESPONSE" = "y" ] || [ "$DREVOPS_AHOY_CONFIRM_RESPONSE" = true ]
+      if [ -z "$AHOY_CONFIRM_RESPONSE" ]; then
+        read -r -p ">> $1 [y/N] " AHOY_CONFIRM_RESPONSE
+        [ "$AHOY_CONFIRM_RESPONSE" = "y" ] || [ "$AHOY_CONFIRM_RESPONSE" = true ] || ( echo "The operation was canceled." && exit 1 )
+      else
+        echo ">> $1 [y/N] $AHOY_CONFIRM_RESPONSE" \
+        && if [ "${AHOY_CONFIRM_WAIT_SKIP}" != "1" ]; then echo "Waiting for 3 seconds... Press Ctrl+C to cancel."; sleep 3; fi
+      fi
     hide: true
 
 # Override entrypoint to alter default behaviour of Ahoy.
@@ -266,11 +261,11 @@ entrypoint:
   # Read variables from .env file, respecting existing environment variable values.
   #
   # It is important to understand that variables set in .env file are already
-  # available inside of the containers after stack is running (as a part of
-  # docker-compose functionality), so most of the commands are using these
+  # available inside the containers after stack is running (as a part of
+  # docker compose functionality), so most of the commands are using these
   # values taken from containers.
   #
-  # However, since docker does not support changes to environment variables in
+  # However, since Docker does not support changes to environment variables in
   # running containers without restarting containers, we are adding this
   # mechanism of reading variables here to allow adjustments of some variables
   # (like PHPCS scan targets) without the need to restart containers.
@@ -279,7 +274,5 @@ entrypoint:
   - |
     t=$(mktemp) && export -p > "$t" && set -a && . ./.env && if [ -f ./.env.local ];then . ./.env.local;fi && set +a && . "$t" && rm "$t" && unset t
     bash -e -c "$0" "$@"
-  # Replaced with your command.
   - '{{cmd}}'
-  # The name of the command that was run (available as $0).
   - '{{name}}'
