Updated provision commands to install govcms or normal civictheme drupal dependencies.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -234,6 +234,10 @@ commands:
   provision-minimal:
     usage: Provision with minimal profile (no sub-theme).
     cmd: |
+      if ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile detected. Reinstalling default composer dependencies." &&
+        ahoy composer install
+      fi
       export DRUPAL_PROFILE=minimal &&
       export CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=1 &&
       ahoy provision && ahoy info
@@ -241,12 +245,20 @@ commands:
   provision-minimal-subtheme:
     usage: Provision with minimal profile (with sub-theme).
     cmd: |
+      if ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile detected. Reinstalling default composer dependencies." &&
+        ahoy composer install
+      fi
       export DRUPAL_PROFILE=minimal &&
       ahoy provision && ahoy info
 
   provision-govcms:
     usage: Provision with GovCMS profile (no sub-theme).
     cmd: |
+      if ! ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile not found. Installing GovCMS composer dependencies." &&
+        ahoy composer-install-govcms
+      fi
       export DRUPAL_PROFILE=govcms &&
       export CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=1 &&
       export COMPOSER=composer.govcms.json &&
@@ -255,6 +267,10 @@ commands:
   provision-govcms-subtheme:
     usage: Provision with GovCMS profile (with sub-theme).
     cmd: |
+      if ! ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile not found. Installing GovCMS composer dependencies." &&
+        ahoy composer-install-govcms
+      fi
       export DRUPAL_PROFILE=govcms &&
       export COMPOSER=composer.govcms.json &&
       ahoy provision && ahoy info
@@ -262,6 +278,10 @@ commands:
   provision-govcms-subtheme-sibling:
     usage: Provision with GovCMS profile (sub-theme as sibling).
     cmd: |
+      if ! ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile not found. Installing GovCMS composer dependencies." &&
+        ahoy composer-install-govcms
+      fi
       export DRUPAL_PROFILE=govcms &&
       export CIVICTHEME_INSTALL_SIBLING=1 &&
       export COMPOSER=composer.govcms.json &&
@@ -270,6 +290,10 @@ commands:
   provision-content-corporate:
     usage: Provision with corporate content profile.
     cmd: |
+      if ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile detected. Reinstalling default composer dependencies." &&
+        ahoy composer install
+      fi
       export CIVICTHEME_CONTENT_PROFILE=corporate &&
       export CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=1 &&
       ahoy provision && ahoy info
@@ -277,6 +301,10 @@ commands:
   provision-content-highereducation:
     usage: Provision with higher education content profile.
     cmd: |
+      if ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile detected. Reinstalling default composer dependencies." &&
+        ahoy composer install
+      fi
       export CIVICTHEME_CONTENT_PROFILE=highereducation &&
       export CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=1 &&
       ahoy provision && ahoy info
@@ -284,6 +312,10 @@ commands:
   provision-content-government:
     usage: Provision with government content profile.
     cmd: |
+      if ahoy cli "test -d /app/web/profiles/contrib/govcms" 2>/dev/null; then
+        echo "[INFO] GovCMS profile detected. Reinstalling default composer dependencies." &&
+        ahoy composer install
+      fi
       export CIVICTHEME_CONTENT_PROFILE=government &&
       export CIVICTHEME_SUBTHEME_ACTIVATION_SKIP=1 &&
       ahoy provision && ahoy info
